### ISSUE TITLE
Decimate saying you have less than the amount of Tris already 

### ISSUE THREAD

**Issue by Xilosc** [GiveMeAllYourCats/cats-blender-plugin#192]
trying to decimate a model with 74,138 Tris to 70k but in both 2.79 and 2.82 it just tells me I already have less than the selected Tris so nothing was done. I tried lowering the decimate number to 65k but still told me I had less than that already. Not sure what's going on.

**Comment by feilen** [comment]
Probably a symptom of how we used to count tris (e.g. just getting the total count of faces, which didn't work for quads). This has been fixed as of the most recent release.
