### ISSUE TITLE
Error in Armature.py on Fix Model for a Blender Rigify model with extra bones

### ISSUE THREAD

**Issue by Xqua** [GiveMeAllYourCats/cats-blender-plugin#194]
Hi, I'm trying to clean a model I made from scratch and rigged with the Blender plugin Rigify.

But when I click the Fix Model button I get this error:

```Traceback (most recent call last):
  File "/home/xqua/.config/blender/2.80/scripts/addons/cats-blender-plugin-master/tools/armature.py", line 1086, in execute
    if vg.name not in bones_to_delete:
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x90 in position 0: invalid start byte

location: <unknown location>:-1
```

Any idea what could be wrong ?

**Comment by Darkblader24** [comment]
This error seems to be very random and I have not yet found a fix for this. It should eventually work if you try it a couple times more.
