### ISSUE TITLE
CATS can't connect to Google for mesh translations

### ISSUE THREAD

**Issue by StarFoxFan11** [GiveMeAllYourCats/cats-blender-plugin#197]
The only thing that seems to translate are the bones, the Shape Keys, Mesh, and Meshes and Objects buttons give me the "Can't connect to google. Please check your internet connection" error.

**Comment by Darkblader24** [comment]
You are using an outdated cats version, try installing the lastest version.

**Comment by Arcticgamez** [comment]
im also on version 0.19.0 which is the newest one and it keeps saying this error msg
