### ISSUE TITLE
Cats in 2.8 way slower than in 2.79

### ISSUE THREAD

**Issue by snokey** [GiveMeAllYourCats/cats-blender-plugin#198]
Ryzen 3600
32gb ram
5700 amd gpu
SSD

Clicking on apply rest pose takes up to 5 minutes compared to seconds on 2.79, same with merging all meshes.

**Comment by Darkblader24** [comment]
This is very likely an issue with Blender, not with Cats. Test if the same issue still occurs in Blender 2.90
