### ISSUE TITLE
Error When Importing + Fixing Models

### ISSUE THREAD

**Issue by friendfrog** [GiveMeAllYourCats/cats-blender-plugin#199]
I have a fresh install of Blender (2.83 LTS) and CATS plugin (I've tried 17.0 and 17.1-dev)
Whenever I try importing models I get this error message 
![image](https://user-images.githubusercontent.com/55005591/89087540-449eda00-d35a-11ea-92ca-ddc282c7c528.png)
If I press the Fix button I get this error message.
![image](https://user-images.githubusercontent.com/55005591/89087562-52545f80-d35a-11ea-89b8-09fbb3cd24a1.png)
I can send the model + any additional info you need if that would help.

**Comment by Darkblader24** [comment]
Thanks for the report, this is now fixed in the development version of cats and will be released soon. For now you can just install the development version in cats via the build-in updater.
