### ISSUE TITLE
Exported FBX imported in Unity has strange behavior when using blendshapes

### ISSUE THREAD

**Issue by theshinyknight** [GiveMeAllYourCats/cats-blender-plugin#203]
Got different models exported via CATS; and they all show a similar issue: when using blendshapes, the model shader change.

For some models it is easier to notice than for others, but they all share the same behavior: the shadow and the overall shader in Unity does change when using blendshapes.

![before blendshape](https://user-images.githubusercontent.com/7696251/91013934-5ceec700-e59d-11ea-9027-bbafd06a9f2b.JPG)

![after blendshape](https://user-images.githubusercontent.com/7696251/91013942-611ae480-e59d-11ea-8b70-51b07d8a7c6a.JPG)

This reproduce using MMD, XPS or even Vroid files; once exported as FBX and imported into Unity3d

You can see the artifacts appearing on the tip of her hair, on the neck area and on the armpits area; looks like the shadows or the reflectivity of the material does change. In some models you can see noticeable artifacts on the mouth and nose area too, which are quite noticeable especially if you are animating in real time the model.

**Comment by JordoVR** [comment]
@theshinyknight I believe that is not a CATS issue but rather the fact that you did not tick "Legacy Blend Shape Normals" in the model FBX import options within Unity.
![image](https://user-images.githubusercontent.com/9134625/91421723-8e45ec00-e856-11ea-91f9-e9fcae403640.png)

If this is for VRChat, it should give you a warning about this when you try to upload it on the latest SDK, as it also balloons the size of the model alongside the normals issue.

**Comment by Darkblader24** [comment]
This doesn't look like a cats issue and a solution is provided, so I will close this.
