### ISSUE TITLE
Eye Tracking Roaming

### ISSUE THREAD

**Issue by Nierfenhimer** [GiveMeAllYourCats/cats-blender-plugin#207]
When testing eye tracking, from what can be deciphered, rotation on both x and y axes takes on a "drift" that causes a kind of false momentum which causes the eyes to continue moving for several values in the previous direction when the direction is reversed.

Resolution appears to come from changing the viewport type (in most cases, from "solid" to "material preview"), but sometimes does not help. Restarting Blender seems to help in resolution. Opening certain software (in this case, OBS) causes the issue to compound irrationally, in one case causing the eyes to pop forward out of the head and down as if falling out. This also ceased when restarting Blender.

Example video:
https://youtu.be/sw_MokdkpjU

**Comment by Darkblader24** [comment]
Thanks for the report, this is now fixed in the development version of cats and will be released soon. For now you can just install the development version in cats via the build-in updater.
