### ISSUE TITLE
When Doing Fix Model Issues Come Up

### ISSUE THREAD

**Issue by ShadowQween** [GiveMeAllYourCats/cats-blender-plugin#208]
I get issues when I do fix model and doing other things like combine armature with meshes. I am trying to get an mmd model have the meshes combined onto the model so when I pose it it will move with the meshes which is the clothes for it,

![Blender Info Log 9_11_2020 8_09_15 AM_LI_Moment(2)]
(https://user-images.githubusercontent.com/71134951/92930336-89ad3600-f407-11ea-8b50-446ed454cc96.jpg)

**Comment by kirigaine** [comment]
I've been having the same issue. I couldn't resolve it, but with following the traceback and a small google search I found this:

https://blender.stackexchange.com/questions/187699/2-90-keyword-apply-as-unrecognized-error

The code format seems to have changed slightly in the newer blender versions and might need changed as per the comment?
Skimming the code and editing in the new format myself didn't seem to work.

**Comment by Darkblader24** [comment]
Thanks for the report, this is fixed in the development version of cats and will be released soon. For now you can just install the development version in cats via the build-in updater.
