### ISSUE TITLE
"Fixed Model" button is not working properly

### ISSUE THREAD

**Issue by XXDarkK3NXX** [GiveMeAllYourCats/cats-blender-plugin#209]
It said here:

bpy.ops.cats_armature.fix()
Traceback (most recent call last):
  File "G:\SteamLibrary\steamapps\common\Blender\2.90\scripts\addons\cats-blender-plugin-master\tools\armature.py", line 244, in execute
    context.scene.view_settings.view_transform = 'Standard'
TypeError: bpy_struct: item.attr = val: enum "Standard" not found in ('sRGB OETF', 'Non-Colour Data', 'Linear Raw', 'Filmic Log Encoding Base')

location: <unknown location>:-1

**Comment by XXDarkK3NXX** [comment]
The only fix is I have to reinstall blender everytime

**Comment by Darkblader24** [comment]
Will be fixed in the next version, thanks for the report
