### ISSUE TITLE
CATS Plug in isnt working for me  :C please HELP!

### ISSUE THREAD

**Issue by RankaChan** [GiveMeAllYourCats/cats-blender-plugin#214]
So i'm using the newer blender 2.79 and CATS Pluggin isnt working on it for me 
please can someone help on this issue please :C   
![Capture](https://user-images.githubusercontent.com/72422773/95645814-990bb780-0a77-11eb-9d58-b3e204f6679d.PNG)

**Comment by feilen** [comment]
This looks like an issue with your blender installation. Try installing it from the blender website?

**Comment by Darkblader24** [comment]
Or, if you have a custom Python version installed, try removing that from the environment variables
