### ISSUE TITLE
"Fix Model" function not working and spits out an error.

### ISSUE THREAD

**Issue by Neropro117** [GiveMeAllYourCats/cats-blender-plugin#215]
When I load up a model and try to fix it with the button, I just get an error. I made screenshots on before and after I click "Fix Model". I will also send the files that the error mentions.

https://drive.google.com/file/d/1PifbHPfnG_V0hqopVbfCUjAOmxqe3WyL/view?usp=sharing
https://drive.google.com/file/d/17H1oBjMT4DpreBsZNqhWBtlLoj8iF9Ti/view?usp=sharing

![Before](https://user-images.githubusercontent.com/46758921/96366888-cb3da900-114a-11eb-9c73-d12ca4f0be5e.png)
![After](https://user-images.githubusercontent.com/46758921/96366886-ca0c7c00-114a-11eb-8458-887371d94e20.png)

**Comment by VictorienXP** [comment]
This issue is fixed on the development branch of the cats-blender-plugin.
@Neropro117 you can either use the development build of cats-blender-plugin or use Blender 2.83 LTS.

**Comment by Neropro117** [comment]
Thank you, works perfectly fine now.^^
