### ISSUE TITLE
CATS Decimation tool will not work regardless of mode

### ISSUE THREAD

**Issue by Thawxtem** [GiveMeAllYourCats/cats-blender-plugin#223]
I keep trying to decimate my vrm model imported using the CATS plugin and no matter when I try, or which decimation mode I use, I get the same error message window

![Screenshot (6)](https://user-images.githubusercontent.com/74128498/98458654-a096ad00-2158-11eb-80b5-96d7ae8489e0.png)

CATS 0.17.0
Blender 2.9

**Comment by Darkblader24** [comment]
This issue is fixed in the development version of cats. You can update to it in cats via the built-in updater
