### ISSUE TITLE
Apply as Rest Pose / Pose to Shape key error using Blender 2.9

### ISSUE THREAD

**Issue by Pursec** [GiveMeAllYourCats/cats-blender-plugin#225]
When attempting to Apply as Rest Pose traceback Type error found in the implementation of pose_to_shapekey(). 

This may be an issue caused by changes to ops.py in Blender 2.9 that weren't present in earlier versions

![TraceBack](https://user-images.githubusercontent.com/45805062/98575699-80b1d700-2287-11eb-911f-df753e3e7c18.PNG)

**Comment by Darkblader24** [comment]
Hey, this issue is fixed in the development version of cats. You can update to it via the built-in updater in cats.
