### ISSUE TITLE
Better texture atlasing

### ISSUE THREAD

**Issue by Cazra** [GiveMeAllYourCats/cats-blender-plugin#226]
A few improvement requests in regards to generating texture atlases: 

- When the atlas is created, the atlas image almost always contains a lot of empty space. Could the atlas textures be shrunk down to fit the non-empty space?
- It seems that CATS only atlases the diffuse textures. Can it be extended to also atlas emissive, bump, and other textures?

**Comment by joshthegrate** [comment]
yes please fix this. if I atlas 4 textures of the same resolution I should get an atlas fully filled outwith no dead space also would like to be able to select the end atlas resolution size.

**Comment by feilen** [comment]
Coincidentally, the Bake changes are going to be up soon: https://github.com/feilen/cats-blender-plugin/wiki/Bake

Lets you bake all PBR maps, and packs all islands into one UV space instead of just having all islands in one. Supports UVPackMaster2 Pro for even more densely packed maps.

**Comment by feilen** [comment]
Changes are now in, give them a shot!

**Comment by Cazra** [comment]
Thanks! You're awesome!
