### ISSUE TITLE
cats plug import pmx,vrm file "unicodedecodeerror utf-8" error

### ISSUE THREAD

**Issue by BakaAkari** [GiveMeAllYourCats/cats-blender-plugin#227]
![image](https://user-images.githubusercontent.com/49110837/99896938-1f9af200-2cd0-11eb-982d-a60707d54947.png)

**Comment by Darkblader24** [comment]
This is a random UnicodeDecodeError, which I'm not sure how to fix. Just try it again, it should eventually work.

**Comment by alertedsnake** [comment]
"try it again" doesn't seem to be working for me, any further suggestions?
