### ISSUE TITLE
Join Meshes Crash

### ISSUE THREAD

**Issue by DonovanPhoenix** [GiveMeAllYourCats/cats-blender-plugin#230]
![Untitled](https://user-images.githubusercontent.com/40139772/101562567-54958d00-39d0-11eb-8ff6-cac9aa9db44d.png)

CATS 0.17.0
Blender  2.91.0
Windows 10.0.19042.662

I found this issue when I clicked on the "FIX Model" button, if I uncheck "Join Meshes" then it works.
If you need logs tell me how I get them and I will post.

**Comment by DonovanPhoenix** [comment]
Update: I managed to fix the issue using a Decimation > save, and setting the Tris to less than my model's current, then manually applying the decimation when it crashed for the 2 meshes it had issues with

**Comment by Darkblader24** [comment]
Thanks for the report, this is already fixed in the dev version of cats
