### ISSUE TITLE
Transparency

### ISSUE THREAD

**Issue by Aleizter** [GiveMeAllYourCats/cats-blender-plugin#239]
Not sure, if it's with Blender 2.91 or the Plugin, but I get a transparent model when going into the shading window of Blender.

**Comment by hakanai** [comment]
Could you post a screenshot?

**Comment by hakanai** [comment]
Because for me it's like this:

![image](https://user-images.githubusercontent.com/43236/105552125-99df0580-5d57-11eb-8364-c23490120c00.png)

Repro:

* New project
* Load model
* Fix model
* Open bake tab
* Click Desktop
* Check Transparent
* Bake!

**Comment by feilen** [comment]
I believe that's a bug with Blender's GPU baking. Set you render engine to Cycles and make sure you're set to 'CPU', and see if that helps?

**Comment by hakanai** [comment]
I'll try.

It seems like there should be a checkbox for this.

**Comment by feilen** [comment]
It's a bug that's seldom reproduced, but ideally I'll just come up with a workaround for it that the user has no interaction with.

**Comment by hakanai** [comment]
Is there a ticket over at developer.blender.org we can follow to get updates on the GPU baking getting fixed?

**Comment by feilen** [comment]
This looks relevant, but I'm not sure it's the only one: https://developer.blender.org/T59473
I couldn't find any others, but for now I'll just throw together a workaround.

**Comment by hakanai** [comment]
Just to be perfectly clear, where do I have to set the rendering to CPU?

**Comment by feilen** [comment]
See here: https://www.katsbits.com/codex/render-engine/

Below where you set the render engine, you can set device to 'CPU'.

Make sure you set your render engine to Cycles first.

**Comment by hakanai** [comment]
Yeah, I had set the render engine over in the Rendering tab... where else would I find it?

**Comment by hakanai** [comment]
Nope :(

![image](https://user-images.githubusercontent.com/43236/105555471-9484b980-5d5d-11eb-9d8f-54f4987e2b05.png)

**Comment by feilen** [comment]
Aww man. If you're willing to send me your model I can take a closer look?

Transparency baking in general is somewhat tempermental due to the way it has to try to hackily bake alpha (since it's not supported by Blender) so turning it off may give you okay results, until I can improve the alpha baking consistency.
