### ISSUE TITLE
In some cases the generated CATS Bake material is not applied automatically

### ISSUE THREAD

**Issue by VerserVarlin** [GiveMeAllYourCats/cats-blender-plugin#246]
the atlas feature leaves a huge amount of dead space resulting in extremely large texture files that when compressed in unity become a blurry mess. I just made an atlas that gave me a 16384x8192 where literally half of it is just dead space.

**Comment by feilen** [comment]
Try the bake feature instead, it packs all the islands into one UV space.

**Comment by VerserVarlin** [comment]
that feature gives me nothing but errors and a messed up avatar.
![image](https://user-images.githubusercontent.com/7484173/103462425-0e8fc880-4cf3-11eb-9bd5-5ab65761b0cb.png)

**Comment by VerserVarlin** [comment]
so I finally got it to make baked atlas, the issue is, it is still wasting a ton of space resulting in horrible quality bakes. and  messes up the original model.
![image](https://user-images.githubusercontent.com/7484173/103897657-e244c500-50c1-11eb-9fe6-f3af627926c1.png)
![SCRIPT_diffuse](https://user-images.githubusercontent.com/7484173/103897678-e670e280-50c1-11eb-87ef-b81b96545c36.png)

**Comment by feilen** [comment]
It uses blenders default packing, which is really inefficient, unless you have Uvpackmaster Pro installed. 

The messed up original shouldn't happen though, would you mind sending me your .blend/textures so I can take a closer look?

**Comment by feilen** [comment]
Is it all packed into one corner though? That also shouldn't be happening.

**Comment by VerserVarlin** [comment]
do you have a way I can send it to you that won't be publicly accessible?

**Comment by feilen** [comment]
I haven't tried the standard version but it may work? Lemme take a quick look.

As for sending it, I'm feilen#0909 on discord

**Comment by feilen** [comment]
Standard may work, but I might grab a copy just to make sure. We do tweak some things about 'lock_overlapping', which may cause a failure if those aren't defined in the standard edition... but it's possible they're just ignored.

**Comment by feilen** [comment]
oh! And one thing: try disabling 'prioritize head/eyes', I'm finding that that feature doesn't always work well with avatars with a ton of details, so it'll probably be scaled back by default in a future release.

**Comment by feilen** [comment]
TODOs:
- Autodetect doesn't warn the user if no bsdf node is found, it should instead warn the user and enable Diffuse and Normal only by default. (or maybe all passes?)
- some cases cause the generated CATS Bake material to not be applied, apparently. Need to investigate
