### ISSUE TITLE
Options in Japanese. Need them in English in Blender

### ISSUE THREAD

**Issue by fido-barkin** [GiveMeAllYourCats/cats-blender-plugin#248]
I'm trying to create an avatar for VRChat, and the options for the eyes are in Japanese. I've tried installing gettext so I could translate it through Blender, but I can't seem to figure that out. Is there anyway for me to translate these otions into English, or at least a table so I can see which option I'm actually trying to pick? 
![CATS Translation Issue](https://user-images.githubusercontent.com/76918831/103487582-2f781c80-4dcc-11eb-832d-f299879e71fc.png)

**Comment by Darkblader24** [comment]
In Cats under Model Options there is a translate feature. Just press the Translate All button
