### ISSUE TITLE
Error whilst importing .pmx

### ISSUE THREAD

**Issue by Z2r-YT** [GiveMeAllYourCats/cats-blender-plugin#275]
![image](https://user-images.githubusercontent.com/69476320/116870565-adc5bd80-ac0a-11eb-8e57-99d9ef74d248.png)
no idea how to fix

**Comment by a457872681** [comment]
我也遇到了一模一样的问题

**Comment by Darkblader24** [comment]
Thanks for the report, this is now fixed in the new release version 0.19.0.
