### ISSUE TITLE
weird bug i just got idk how to fix this

### ISSUE THREAD

**Issue by kaumi420** [GiveMeAllYourCats/cats-blender-plugin#278]
i had this bug appear please help it only happens when i try and add a pmx file which i aquired from here 
[its for some reason seems to do this no matter where i even did one off ](http://ys.biligame.com/beyel/)
<img width="1032" alt="Screen Shot 2021-05-18 at 6 46 21 AM" src="https://user-images.githubusercontent.com/84384366/118639699-2f3e5380-b7a6-11eb-86e9-3cf8373fd69d.png">
[i even tried the enemy person and paimon](https://genshin.mihoyo.com/ja/news/detail/5885)
and this happened????? it seems they are same error 
<img width="1033" alt="Screen Shot 2021-05-18 at 7 00 22 AM" src="https://user-images.githubusercontent.com/84384366/118640295-d02d0e80-b7a6-11eb-969d-af91353dbb20.png">

**Comment by Darkblader24** [comment]
Thanks for the report, this is now fixed in the new release version 0.19.0.
