### ISSUE TITLE
cats doesn't work in blender 2.93

### ISSUE THREAD

**Issue by LeoFeroz** [GiveMeAllYourCats/cats-blender-plugin#281]
after blender update cats n works correctly in blender 2.93

does not work activate and when it works when importing the model the fix options do not appear and others are broken

**Comment by welovekah** [comment]
Having the same issue.

**Comment by HcgRandon** [comment]
Facing this issue as well. Error I receive on model import:

![image](https://user-images.githubusercontent.com/6123135/120862817-90f90e80-c557-11eb-9a4a-5e1f8e363c8c.png)

**Comment by 62616b61** [comment]
Installing development version of the plugin fixes the issue.
You can install dev version in `Preferences - Add-ons - Cats Blender Plugin - Install Development Version`.

**Comment by little-ice-fly-fly** [comment]
thankyou

**Comment by windskyxb** [comment]
I have the same problem:
Traceback (most recent call last):
  File "C:\Users\winds\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\cats-blender-plugin-0-18-0\extern_tools\mmd_tools_local\operators\fileio.py", line 159, in execute
    self.__translator = DictionaryEnum.get_translator(self.dictionary)
  File "C:\Users\winds\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\cats-blender-plugin-0-18-0\extern_tools\mmd_tools_local\translations.py", line 323, in get_translator
    return getTranslator(dictionary)
  File "C:\Users\winds\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\cats-blender-plugin-0-18-0\extern_tools\mmd_tools_local\translations.py", line 171, in getTranslator
    elif csvfile in bpy.data.texts:
TypeError: bpy_prop_collection.__contains__: expected a string or a tuple of strings

**Comment by DJJabek** [comment]
> I have the same problem:
> Traceback (most recent call last):
> File "C:\Users\winds\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\cats-blender-plugin-0-18-0\extern_tools\mmd_tools_local\operators\fileio.py", line 159, in execute
> self.__translator = DictionaryEnum.get_translator(self.dictionary)
> File "C:\Users\winds\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\cats-blender-plugin-0-18-0\extern_tools\mmd_tools_local\translations.py", line 323, in get_translator
> return getTranslator(dictionary)
> File "C:\Users\winds\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\cats-blender-plugin-0-18-0\extern_tools\mmd_tools_local\translations.py", line 171, in getTranslator
> elif csvfile in bpy.data.texts:
> TypeError: bpy_prop_collection.**contains**: expected a string or a tuple of strings

Have exactly same problem, and I see you have Lumine profile picture so I guess you tried to import Genshin Impact models as well as me xD

**Comment by Darkblader24** [comment]
Thanks for the reports, this is now fixed in the new release version 0.19.0.
