### ISSUE TITLE
AttributeErrpr: 'CATS_IMPORTER_OT_export_model' object has no attribute "action"

### ISSUE THREAD

**Issue by Chekote** [GiveMeAllYourCats/cats-blender-plugin#283]
Howdy,

I get this error every time I try to export my model using CATS in Blender 2.93. Is there a compatibility issue?

<img width="679" alt="Screenshot 2021-06-06 180916" src="https://user-images.githubusercontent.com/550486/120943072-55df1280-c6f2-11eb-9bdd-ec2532651e17.png">

**Comment by sepffuzzball** [comment]
I am also having an issue with this particular error on 2.93. No issue on a 2.90.1 install

**Comment by VeikkoLehmuskorpi** [comment]
I had this issue as well on 2.93.0. No issues on 2.92.0.

**Comment by Darkblader24** [comment]
Thanks for the report, this is now fixed in the new release version 0.19.0.

**Comment by ZarephLae** [comment]
> 
> 
> Thanks for the report, this is now fixed in the new release version 0.19.0.

No it hasn't. xD
