### ISSUE TITLE
fix model button missing

### ISSUE THREAD

**Issue by HarryBols** [GiveMeAllYourCats/cats-blender-plugin#284]
I'm not getting the fix model button

**Comment by Darkblader24** [comment]
Thanks for the report, this is now fixed in the new release version 0.19.0

**Comment by 420Aha-yeet** [comment]
> Thanks for the report, this is now fixed in the new release version 0.19.0

This is still not fixed

**Comment by AAHHHHHHHHHHHhhHhhhHHHHHhHhhhhH** [comment]
Yeah, this same issue is happening for me. It was working in the 0.18.0 version that I had previously installed, then when I installed the 0.19.0 version, the fix model button disappeared.
