### ISSUE TITLE
No properties? Can't open pmx files

### ISSUE THREAD

**Issue by 123madoxua** [GiveMeAllYourCats/cats-blender-plugin#285]
Hello. I tried opening a PMX file. After the new update, I couldn't get to open them anymore.
![image](https://user-images.githubusercontent.com/85820299/121798029-7a893c00-cc56-11eb-893c-2492a4fae434.png)
Please help.

**Comment by Darkblader24** [comment]
Thanks for the report, this is now fixed in the new release version 0.19.0.
