### ISSUE TITLE
Wont Import Models

### ISSUE THREAD

**Issue by meeeeee1134334** [GiveMeAllYourCats/cats-blender-plugin#288]
![Screenshot (250)](https://user-images.githubusercontent.com/86082024/122474595-1386c280-cf89-11eb-8c48-d47277ab6d7d.png)
it shows this error when i import models i want to add

**Comment by JustToad** [comment]
same

**Comment by Darkblader24** [comment]
Thanks for the report, this is now fixed in the new release version 0.19.0
