### ISSUE TITLE
2.9.3 - "TypeError: '_PropertyDeferred' object is not iterable"

### ISSUE THREAD

**Issue by Clarandra** [GiveMeAllYourCats/cats-blender-plugin#289]
This occurs whenever I try to import an object. How can I fix this? I've already reopened Blender and tried to reinstall CATS multiple times.
![cats 1](https://user-images.githubusercontent.com/86097452/122519197-912deb00-cfe8-11eb-8af7-98ec6cba0a72.png)

**Comment by starkitten20** [comment]
This occurs whenever I try it as well very frustrating

**Comment by Darkblader24** [comment]
Thanks for the report, this is now fixed in the new release version 0.19.0
