### ISSUE TITLE
python traceback 

### ISSUE THREAD

**Issue by JustToad** [GiveMeAllYourCats/cats-blender-plugin#291]
Python: Traceback (most recent call last):
  File "C:\Users\Benjamin\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\cats-blender-plugin-0-18-0\tools\importer.py", line 98, in execute
    for f in self.files:
TypeError: '_PropertyDeferred' object is not iterable

location: <unknown location>:-1

thats the error

**Comment by ltsNotSketchy** [comment]
I have been having the same problem and would also like to know how to fix this error.

**Comment by Darkblader24** [comment]
Thanks for the report, this is now fixed in the new release version 0.19.0
