### ISSUE TITLE
"Apply as Rest Pose" button is missing

### ISSUE THREAD

**Issue by aaronfranke** [GiveMeAllYourCats/cats-blender-plugin#293]
Before, CATS had a button for "Apply as Rest Pose":

![](https://i.stack.imgur.com/Ylrt1.png)

Now, with Blender 2.93.1 and the latest CATS master, this button seems to be missing:

![Screenshot from 2021-06-27 00-23-17](https://user-images.githubusercontent.com/1646875/123532777-26626b00-d6de-11eb-92a6-060cc52873b0.png)

This is quite annoying, as this button is pretty much the only reason I use CATS, and now it's gone. Please add it back :)

**Comment by Darkblader24** [comment]
Thanks for the report, this is now fixed in the new release version 0.19.0
